export type User = {
  id: number
  firstName: string
  lastName: string
  email: string
  phone: string
  password: string
}

/**
 * The set of columns the table is allowed to sort by.
 * Deriving this from `User` keeps sorting type-safe: you can never
 * dispatch a sort for a key that doesn't exist on the model.
 */
export type SortableKey = Extract<
  keyof User,
  "id" | "firstName" | "lastName" | "email"
>

export type SortOrder = "asc" | "desc"

/**
 * Payload accepted by the "add user" flow. The id is generated by
 * the reducer, so callers never supply it.
 */
export type NewUser = Omit<User, "id">
